.. Getting Started

はじめよう
---------------

.. This part of the guide focuses on setting up your Python environment.

このパートではPython環境の設定についていくつかのガイドを紹介します。

.. toctree::
   :maxdepth: 2

   starting/which-python

.. - Properly Install Python

- 適切なPythonインストール

 .. toctree::
    :maxdepth: 1

    starting/install/osx
    starting/install/win
    starting/install/linux



.. Writing Great Code

偉大なコードを書く
------------------

.. This part of the guide focuses on best practices for writing Python code.

このパートではPythonコードを書く際のベストプラクティスを紹介します。

.. toctree::
   :maxdepth: 2

   writing/structure
   writing/style
   writing/documentation
   writing/tests
   writing/license



.. Scenario Guide

シナリオガイド
--------------

.. This part of the guide focuses on tool and module advice based on
.. different scenarios.

このパートではシナリオ別にどのようなツールやモジュールを使うと良いのか
アドバイスします。

.. toctree::
   :maxdepth: 2

   scenarios/client
   scenarios/web
   scenarios/cli
   scenarios/gui
   scenarios/db
   scenarios/admin
   scenarios/ci
   scenarios/speed
   scenarios/scientific
   scenarios/imaging


.. Shipping Great Code

偉大なコードを出荷する
---------------------------

.. This part of the guide focuses on deploying your Python code.

このパートではPythonコードをデプロイする際のガイドを紹介します。


.. toctree::
   :maxdepth: 2

   shipping/packaging
   shipping/freezing


.. Development Environment

開発環境
-----------------------

.. toctree::
   :maxdepth: 2

   dev/env
   dev/virtualenvs




.. Additional Notes

その他のノート
----------------

.. This part of the guide, which is mostly prose, begins with some
.. background information about Python, then focuses on next steps.

このパートはほとんどが参考文献の紹介ですが、Pythonの背景についての情報や、
次のステップについて紹介します。

.. toctree::
   :maxdepth: 2

   intro/duction
   intro/community
   intro/learning
   intro/documentation
   intro/news




--------------------------------------

.. Contibution notes and legal information are here (for those interested).

このドキュメントに貢献する方法や、法的な情報です(興味がある人向け)。

.. toctree::
   :maxdepth: 2

   notes/contribute
   notes/license
   notes/styleguide





